apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: sms-checker
  labels:
    app: sms-checker
    component: app-service
spec:
  type: ClusterIP
  selector:
    app: sms-checker
    component: app-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
