{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sms-app-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sms-spam-detector.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations (and .Values.ingress.rateLimit.enabled (or .Values.ingress.rateLimit.rpm .Values.ingress.rateLimit.rps .Values.ingress.rateLimit.burst .Values.ingress.rateLimit.connections .Values.ingress.rateLimit.statusCode)) }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.ingress.rateLimit.enabled .Values.ingress.rateLimit.rpm }}
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.ingress.rateLimit.rpm }}"
    {{- if .Values.ingress.rateLimit.burst }}
    nginx.ingress.kubernetes.io/limit-burst: "{{ .Values.ingress.rateLimit.burst }}"
    {{- end }}
    {{- end }}
    {{- if and .Values.ingress.rateLimit.enabled .Values.ingress.rateLimit.rps }}
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.rateLimit.rps }}"
    {{- end }}
    {{- if and .Values.ingress.rateLimit.enabled .Values.ingress.rateLimit.connections }}
    nginx.ingress.kubernetes.io/limit-connections: "{{ .Values.ingress.rateLimit.connections }}"
    {{- end }}
    {{- if and .Values.ingress.rateLimit.enabled .Values.ingress.rateLimit.statusCode }}
    nginx.ingress.kubernetes.io/limit-req-status-code: "{{ .Values.ingress.rateLimit.statusCode }}"
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /metrics
        pathType: Exact
        backend:
          service:
            name: {{ .Values.appService.name }}
            port:
              number: {{ .Values.appService.service.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appService.name }}
            port:
              number: {{ .Values.appService.service.port }}
{{- end }}
