{{- if .Values.modelService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modelService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sms-spam-detector.modelService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.modelService.service.type }}
  ports:
  - port: {{ .Values.modelService.service.port }}
    targetPort: {{ .Values.modelService.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "sms-spam-detector.modelService.selectorLabels" . | nindent 4 }}
{{- end }}
