{{- if .Values.modelService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.modelService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sms-spam-detector.modelService.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.modelService.replicas }}
  selector:
    matchLabels:
      {{- include "sms-spam-detector.modelService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sms-spam-detector.modelService.selectorLabels" . | nindent 8 }}
        component: backend
        version: {{ .Values.modelService.versionLabel | quote }}
    spec:
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}
      containers:
      - name: {{ .Values.modelService.name }}
        image: {{ include "sms-spam-detector.modelService.image" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
          name: http
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MODEL_INTERNAL_PORT
        - name: MODEL_VERSION
          value: {{ .Values.modelService.modelVersion | quote }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: model-files
          mountPath: /models
          readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.modelService.resources | nindent 10 }}
        {{- if .Values.modelService.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.modelService.livenessProbe.path }}
            port: {{ .Values.modelService.service.port }}
          initialDelaySeconds: {{ .Values.modelService.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.modelService.livenessProbe.periodSeconds }}
        {{- end }}
        {{- if .Values.modelService.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.modelService.readinessProbe.path }}
            port: {{ .Values.modelService.service.port }}
          initialDelaySeconds: {{ .Values.modelService.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.modelService.readinessProbe.periodSeconds }}
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: model-files
        persistentVolumeClaim:
          claimName: model-files-pvc
      {{- end }}
{{- end }}
