apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "sms-spam-detector.labels" . | nindent 4 }}
    {{- if .Values.istio.enabled }}
    istio-injection: enabled
    {{- end }}
