apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: sms-checker
  labels:
    app: sms-checker
    component: model-service
spec:
  type: ClusterIP
  selector:
    app: sms-checker
    component: model-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  sessionAffinity: None
